print("Cristine Joy C. Mayores")
print("Capayang, Mogpog, Marinduque")
print("July 5, 2004")
print("College of Information and Computing Sciences")
print("Bachelor of Science in Information Technology")
print("2nd Year")
print("2B")
print("Dancing")
print("Watching kdrama")
print("Reading webtoon and comics")
print("Playing sudoku puzzles")
print("Drawing digital arts")